//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingSystemEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Værktøj
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Værktøj()
        {
            this.Udlejning = new HashSet<Udlejning>();
        }
    
        public int VærktøjId { get; set; }
        public string Værktøjsnavn { get; set; }
        public string Beskrivelse { get; set; }
        public double depositum { get; set; }
        public double døgnpris { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Udlejning> Udlejning { get; set; }

    }
}
